version: 2.1

executors:
  jdk21:
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    machine:
      image: ubuntu-2004:202104-01
      docker_layer_caching: true
  jdk22:
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    machine:
      image: ubuntu-2004:202104-01
      docker_layer_caching: true
  jdk23:
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    machine:
      image: ubuntu-2004:202104-01
      docker_layer_caching: true

jobs:
  jdk21-ci:
    executor: jdk21
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y openjdk-21-jdk
      - checkout
      - run: ./gradlew build
  jdk22-ci:
    executor: jdk22
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y openjdk-22-jdk
      - checkout
      - run: ./gradlew build
  jdk23-ci:
    executor: jdk23
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y openjdk-23-jdk
      - checkout
      - run: ./gradlew build

workflows:
  gradle-build:
    jobs:
      - jdk21-ci
      - jdk22-ci
      - jdk23-ci
