version: 2.1

jobs:
  jdk21-ci:
    docker:
      - image: cimg/openjdk:21.0.5

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      architecture: "amd64"
      platform: "linux/amd64"

    steps:
      - checkout
      - run: ./gradlew build

  jdk22-ci:
    docker:
      - image: cimg/openjdk:22.0.2

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      architecture: "amd64"
      platform: "linux/amd64"

    steps:
      - checkout
      - run: ./gradlew build

  jdk23-ci:
    docker:
      - image: cimg/openjdk:23.0.1

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      architecture: "amd64"
      platform: "linux/amd64"

    steps:
      - checkout
      - run: ./gradlew build

workflows:
  gradle-build:
    jobs:
      - jdk21-ci
      - jdk22-ci
      - jdk23-ci
