version: 2.1

orbs:
  tcc: atomicjar/testcontainers-cloud-orb@0.1.0

executors:
  jdk21:
    docker:
      - image: cimg/openjdk:21.0.5
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
  jdk22:
    docker:
      - image: cimg/openjdk:22.0.2
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
  jdk23:
    docker:
      - image: cimg/openjdk:23.0.1
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

jobs:
  jdk21-ci:
    executor: jdk21
    steps:
      - checkout
      - run: ./gradlew build
  jdk22-ci:
    executor: jdk22
    steps:
      - checkout
      - run: ./gradlew build
  jdk23-ci:
    executor: jdk23
    steps:
      - checkout
      - run: ./gradlew build

workflows:
  gradle-build:
    jobs:
      - jdk21-ci:
          pre-steps:
            - tcc/setup
      - jdk22-ci:
          pre-steps:
            - tcc/setup
      - jdk23-ci:
          pre-steps:
            - tcc/setup
