server:
  port: 8092

spring:
  # elasticsearch
  elasticsearch:
    uris:
      - http://elasticsearch.livk.com:9200
    username: elastic
    password: livk123
    connection-timeout: 30s
    socket-timeout: 30s