name: CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distribution: [ temurin ]
        java: [ 21, 22 ]

    name: JDK ${{ matrix.java }} CI with Gradle

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4.5.0
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current

      - name: Gradle Run Build
        run: gradle clean build
