# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-cmd "redis-cli config set requirepass 123456"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

      redis-stack:
        image: redis/redis-stack
        ports:
          - 6380:6379
          - 8001:8001

      zookeeper:
        image: zookeeper
        ports:
          - 2181:2181

      rabbitmq:
        image: rabbitmq
        env:
          RABBITMQ_DEFAULT_USER: admin
          RABBITMQ_DEFAULT_PASS: admin
        ports:
          - 5672:5672
          - 15672:15672
          - 15675:15675
          - 1883:1883
        options: >-
          --health-cmd "rabbitmq-plugins enable rabbitmq_mqtt"
          --health-cmd "rabbitmq-plugins enable rabbitmq_web_mqtt"

      pulsar:
        image: apachepulsar/pulsar-standalone
        ports:
          - 6650:6650

      minio:
        image: bitnami/minio
        env:
          MINIO_ROOT_USER: admin
          MINIO_ROOT_PASSWORD: 1375632510
        ports:
          - 9010:9000

      click-house:
        image: clickhouse/clickhouse-server
        ports:
          - 18123:8123
          - 19000:9000
          - 19009:9009

      postgresql:
        image: gradescope/postgresql-multiple-databases
        ports:
          - 5432:5432
        env:
          POSTGRES_MULTIPLE_DATABASES: graphql,mybatis,mybatis_type
          POSTGRES_PASSWORD: 123456

      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: 123456
        ports:
          - 3306:3306

    steps:
      - name: Set up host
        run: echo '127.0.0.1 livk.com' | sudo tee -a /etc/hosts

      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: cleanAll build -D exclude=true
          gradle-version: current

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coveralls-repo-token: ${{ secrets.COVERALLS_REPO_TOKEN }}

