name: Jdk 23 CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 23
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 23
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current
          cache-read-only: false
          cache-write-only: true

      - name: Gradle Run Build
        run: gradle clean build
