name: Jdk 22 CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up host
        run: echo '127.0.0.1 livk.com' | sudo tee -a /etc/hosts

      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 22
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 22
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current

      - name: Gradle Run Build
        run: gradle clean build
